version: 2.1

jobs:
  e2e:
    parameters:
      php-version:
        type: string
      zipkin-php-version:
        type: string
    docker:
      # node-browsers come with java pre-installed
      - image: cimg/php:<< parameters.php-version >>-browsers
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    working_directory: ~/zipkin-php-example
    steps:
      - checkout
      - run:
          name: Install Composer
          command: |
            php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
            php -r "if (hash_file('SHA384', 'composer-setup.php') === trim(file_get_contents('https://composer.github.io/installer.sig'))) { echo 'Installer verified'; } else { echo 'Installer invalid'; unlink('composer-setup.php'); } echo PHP_EOL;"
            php composer-setup.php
            php -r "unlink('composer-setup.php');"
      - run: composer require openzipkin/zipkin:"^<< parameters.zipkin-php-version >>"
      - run: composer install -n
      - run: curl -sSL https://zipkin.io/quickstart.sh | bash -s
      - run:
          background: true
          command: java -jar zipkin.jar
      # block until zipkin is available
      - run: wget --retry-connrefused -T 60 -O /dev/null http://127.0.0.1:9411/health
      # start both processes in the background, but don't use composer as it dies
      - run:
          background: true
          command: php -S '127.0.0.1:8081' frontend.php
      - run:
          background: true
          command: php -S '127.0.0.1:9000' backend.php
      # hit the frontend which calls the backend
      - run: wget -v --retry-connrefused -T 5 -O /dev/null 127.0.0.1:8081
      - run: |
          # wait just in case
          sleep 1
          test $(curl -s 127.0.0.1:9411/api/v2/traces | jq '.[0] | length') -eq 4

workflows:
  version: 2
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - e2e:
          context:
            - docker-hub-credentials
          matrix:
            parameters:
              php-version: ["7.4", "8.0", "8.1"]
              zipkin-php-version: ["3.0.0"]
  all-tests:
    jobs:
      - e2e:
          context:
            - docker-hub-credentials
          matrix:
            parameters:
              php-version: ["7.4", "8.0", "8.1"]
              zipkin-php-version: ["3.0.0"]
