server:
  port: 8090

spring:
  application:
    name: dubbo-samples-privider-springCloud

dubbo:
  application:
    name: ${spring.application.name}
  registry:
    address: zookeeper://192.168.150.13:2181
    timeout: 2000
  protocol:
    name: dubbo
    port: 20890
  # 扫描 @DubboService 注解
  scan:
    base-packages: com.sxliusir.provider.service